#!/usr/bin/python
# This script will check if your operating system is ready to download and visualize data from ESGF
# Author: Arildo Oliveira

import os
import subprocess
import sys

# variables
os_name = subprocess.check_output('uname', shell=True)
apt_system_list = ['Ubuntu', 'Xubuntu', 'Kubuntu', 'Lubuntu', 'Debian']
yum_system_list = ['Fedora', 'Red', 'Korora', 'CentOS']


# defs
def check_wget(os_distro, apt_system_list, yum_system_list):
    print("\nChecking if wget is installed...")
    if (os_distro in yum_system_list):
        print("Dependency required, installing dpkg...")
        try:
            os.system('yum install -y dpkg &>/dev/null')
        except os.error:
            print("An error has ocurred, please try again.")
            sys.exit()
        print("")
    wget_status = subprocess.check_output("echo $(dpkg-query -W -f='${Status}' wget 2>/dev/null | grep -c 'ok installed')", shell=True)
    print(wget_status)

os.system('cls' if os.name == 'nt' else 'clear')

# check if the script has the right privileges
if 'root' not in subprocess.check_output('whoami', shell=True):
    sys.exit()

print('This script will check if your system is ready to download and visualize data from ESGF')
raw_input('\nPress any key to start...')

if ('Darwin' in os_name):  # os is mac
    print('mac')
elif ('Linux' in os_name):  # os is linux
    os_distro = subprocess.check_output('cat /etc/issue', shell=True).split()[0]
    print('Operating System: ')
    print(os_distro)
    check_wget(os_distro, apt_system_list, yum_system_list)
else:  # os is windows
    print('windows')
