#!/usr/bin/python
# This script will check if your operating system is ready to download and visualize data from ESGF
# Author: Arildo Oliveira

import os
import subprocess
import sys

# variables
os_name = subprocess.check_output('uname', shell=True)
apt_system_list = ['Ubuntu', 'Xubuntu', 'Kubuntu', 'Lubuntu', 'Debian']
yum_system_list = ['Fedora', 'Red', 'Korora', 'CentOS']
os_wget = None
os_java = None
os_grads = None
os_ncview = None
os_xcode = None
os_xcode_clt = None
os_homebrew = None


# defs
def clear_cli():  # clears the terminal
    os.system('cls' if os.name == 'nt' else 'clear')


def check_wget_linux():
    global os_distro
    global apt_system_list
    global yum_system_list
    global os_wget

    print("\nChecking if wget is installed...")
    if (os_distro in yum_system_list):
        wget_status = subprocess.check_output("echo $(yum list installed wget 2>/dev/null | grep -c 'Installed Packages')", shell=True)
    if (os_distro in apt_system_list):
        wget_status = subprocess.check_output("echo $(dpkg-query -W -f='${Status}' wget 2>/dev/null | grep -c 'ok installed')", shell=True)
    if ('1' in wget_status):
        print("Wget is already installed")
    elif ('0' in wget_status):
        print("Wget is not installed, installing...")
        try:
            if (os_distro in yum_system_list):
                os.system('yum install -y wget &>/dev/null')
            elif (os_distro in apt_system_list):
                os.system('apt-get install -y wget &>/dev/null')
        except os.error:
            print("An error has ocurred, please try again")
            sys.exit()
        print("Wget installed")
        os_wget = True


def check_java_linux():
    global os_distro
    global apt_system_list
    global yum_system_list
    global os_java

    print("\nChecking if Java is installed...")
    java_status = subprocess.check_output("echo $(java -version 2>&1)", shell=True)
    if ('openjdk' in java_status and ('1.8' in java_status or '1.7' in java_status)):
        print("OpenJDK is already installed")
    elif (("Java(TM)" in java_status) and ('1.8' in java_status or '1.7' in java_status)):
        print("Oracle Java is already installed")
    else:
        print("No Java JDK found, installing...")
        if (os_distro in apt_system_list):
            install_java_apt()
        elif (os_distro in yum_system_list):
            install_java_yum()


def install_java_apt():
    try:
        print("The script will install Java JDK 8 in your system")
        print("Please accept the License Agreement when prompted")
        raw_input('\nPress any key to continue...')
        os.system("add-apt-repository -y ppa:webupd8team/java &>/dev/null")
        os.system("apt-get update &>/dev/null")
        os.system("apt-get install -y oracle-java8-installer")
        os.system("apt-get install -y oracle-java8-set-default")
    except os.error:
        print("An error has ocurred, please try again")
        sys.exit()
    print("Java installed")
    os_java = True


def install_java_yum():
    try:
        print()
    except os.error:
        print("An error has ocurred, please try again")
        sys.exit()
    print("Java installed")
    os_java = True
# end of defs

clear_cli()
if 'root' not in subprocess.check_output('whoami', shell=True):  # check if the script has the right privileges
    print("Must be root to execute the script" +
          "\n[Usage]: sudo ./ESGFready")
    sys.exit()

print('This script will check if your system is ready to download and visualize data from ESGF')
raw_input('\nPress any key to start...')

if ('Darwin' in os_name):  # os is mac
    print('mac')
elif ('Linux' in os_name):  # os is linux
    os_distro = subprocess.check_output('cat /etc/issue', shell=True).split()[0]
    print('Operating System: ')
    print(os_distro)
    check_wget_linux()
    check_java_linux()
else:  # os is windows
    print('windows')
