#!/usr/bin/python
# This script will check if your operating system is ready to download and visualize data from ESGF
# Author: Arildo Oliveira

import os
import subprocess
import sys

# variables
os_name = subprocess.check_output('uname', shell=True)
apt_system_list = ['Ubuntu', 'Xubuntu', 'Kubuntu', 'Lubuntu', 'Debian']
yum_system_list = ['Fedora', 'Red', 'Korora', 'CentOS']
os_wget = None
os_java = None
os_grads = None
os_ncview = None
os_xcode = None
os_xcode_clt = None
os_homebrew = None


# defs
def clear_cli():  # clears the terminal
    os.system('cls' if os.name == 'nt' else 'clear')


def check_wget_linux():
    global os_distro
    global apt_system_list
    global yum_system_list
    global os_wget

    print("\nChecking if wget is installed...")
    if (os_distro in yum_system_list):
        """ installs dpkg in the os with yum package manager
        to be able to query the installed packages and look for wget
        """
        print("Dependency required, installing dpkg...")
        try:
            os.system('yum install -y dpkg &>/dev/null')
        except os.error:
            print("An error has ocurred, please try again")
            sys.exit()
        print("Dependency installed, resuming...")
    wget_status = subprocess.check_output("echo $(dpkg-query -W -f='${Status}' wget 2>/dev/null | grep -c 'ok installed')", shell=True)
    if ('1' in wget_status):
        print("Wget is already installed")
    elif ('0' in wget_status):
        print("Wget is not installed, installing...")
        try:
            if (os_distro in yum_system_list):
                os.system('yum install -y wget &>/dev/null')
            elif (os_distro in apt_system_list):
                os.system('apt-get install -y wget &>/dev/null')
        except os.error:
            print("An error has ocurred, please try again")
            sys.exit()
        print("Wget installed")
        os_wget = True


def check_java_linux():
    global os_distro
    global apt_system_list
    global yum_system_list
    global os_java

    print("\nChecking if java is installed...")
    java_status = subprocess.check_output("echo $(java -version 2>&1)", shell=True)
    if ('openjdk' in java_status and ('1.8' in java_status or '1.7' in java_status)):
        print("OpenJDK is installed")
    elif (("Java(TM)" in java_status) and ('1.8' in java_status or '1.7' in java_status)):
        print("Oracle Java is installed")
    else:
        print("No Java JDK found")
# end of defs

clear_cli()
if 'root' not in subprocess.check_output('whoami', shell=True):  # check if the script has the right privileges
    print("Must be root to execute the script" +
          "\n[Usage]: sudo ./ESGFready")
    sys.exit()

print('This script will check if your system is ready to download and visualize data from ESGF')
raw_input('\nPress any key to start...')

if ('Darwin' in os_name):  # os is mac
    print('mac')
elif ('Linux' in os_name):  # os is linux
    os_distro = subprocess.check_output('cat /etc/issue', shell=True).split()[0]
    print('Operating System: ')
    print(os_distro)
    #check_wget_linux()
    check_java_linux()
else:  # os is windows
    print('windows')
